version: '3'
services:
  app:
    build: .
    container_name:  "fastapicrud"
    restart: always
    volumes: 
      - .:/app
    depends_on: 
      -  db
    ports:
      - "8000:8000"

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_DATABASE: project
